version: '3'
services:
  postgres:
    # the tag was found on docker hub
    image: 'postgres:latest'
    environment:      
      POSTGRES_HOST_AUTH_METHOD: "trust"
  redis:
      image: 'redis:latest'
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
  api:
    build:
      # No need to specify the full path here, just the name
      dockerfile: Dockerfile.dev
      # This is where we specify where the Dockerfile.dev file lives
      context: ./server
    volumes:
      # Bookmark
      - /app/node_modules
      # Map external ./server folder to internal /app folder
      - ./server/:/app
    environment:
      # Most of the following values come from the documentationf or the
      # associated images. 
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      # This is the default postgres default password
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
    depends_on:
      - postgres
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      # Bookmark, do not map
      - /app/node_modules
      # map the external client directory to the internal app directory
      - ./client:/app
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
       
